#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Apr 20 08:22:12 2011

import wx

# begin wxGlade: extracode
# end wxGlade



class GMS(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: GMS.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        #self.button_pressed = wx.ToggleButton(self, -1, "Button pressed")
        self.clicked_window = wx.TextCtrl(self, -1, "")
        self.debug_output = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: GMS.__set_properties
        self.SetTitle("GMS")
        self.clicked_window.SetMinSize((200, 29))
        self.debug_output.SetMinSize((279, 270))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: GMS.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        #sizer_3.Add(self.button_pressed, 0, 0, 0)
        sizer_3.Add(self.clicked_window, 0, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_2.Add(self.debug_output, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade
        
    def setClicked(self, value):
        # self.clicked_window.Value = value
        pass
    def setOutput(self, value):
        
        self.debug_output.SetValue(value)

# end of class GMS


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = GMS(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
